Table Produto [headercolor: #175e7a] {
	ProdutoId uniqueidentifier [ pk, unique ]
	SubcategoriaId uniqueidentifier [ not null ]
	Nome varchar(255) [ not null ]
	Preco smallmoney [ not null ]
	Status tinyint [ not null ]
	ImagemUrl nvarchar(255) [ not null ]
}

Table Usuario [headercolor: #175e7a] {
	UsuarioId uniqueidentifier [ pk, unique ]
	NomeCompleto varchar(255)
	Email varchar(255)
	Celular varchar(20)
	DataNascimento date
	CPF varchar(11)
	Senha varchar(255)
}

Table Endereco [headercolor: #175e7a] {
	EnderecoId uniqueidentifier [ pk, not null, unique ]
	UsuarioId uniqueidentifier [ not null ]
	Estado nvarchar(100)
	Cidade nvarchar(150)
	Bairro varchar(255)
	CEP varchar(8)
	Rua varchar(255)
	Numero integer
	Complemento nvarchar(100)
}

Table Favoritos [headercolor: #175e7a] {
	ProdutoId uniqueidentifier
	UsuarioId uniqueidentifier

	indexes {
		(ProdutoId, UsuarioId) [ name: 'Favoritos_index_1' ]
	}
}

Table Avaliacao [headercolor: #175e7a] {
	AvaliacaoId uniqueidentifier [ pk, unique ]
	UsuarioId uniqueidentifier [ not null ]
	ProdutoId uniqueidentifier [ not null ]
	Comentario varchar(255)
	Nota tinyint
	UpVote bit
}

Table Pedido [headercolor: #175e7a] {
	PedidoId uniqueidentifier [ pk, not null, unique ]
	UsuarioId uniqueidentifier [ not null ]
	EnderecoEntregaId uniqueidentifier [ not null ]
	PagamentoAprovado bit
	Valor smallmoney
	Status tinyint
	Data datetime2
}

Table Pagamento [headercolor: #175e7a] {
	PagamentoId uniqueidentifier [ pk, not null, unique ]
	PedidoId uniqueidentifier [ not null ]
	Metodo tinyint [ not null ]
	Status tinyint [ not null ]
	Valor smallmoney [ not null ]
	DataPagamento datetime2

	indexes {
		(PagamentoId, PedidoId) [ name: 'Pagamento_index_1' ]
	}
}

Table Estoque [headercolor: #175e7a] {
	ProdutoId uniqueidentifier [ pk, not null, unique ]
	Quantidade smallint
}

Table Subcategoria [headercolor: #175e7a] {
	SubcategoriaId uniqueidentifier [ pk, not null, unique ]
	CategoriaId uniqueidentifier [ not null ]
	Nome nvarchar(100)
}

Table Categoria [headercolor: #175e7a] {
	CategoriaId uniqueidentifier [ pk, not null, unique ]
	Nome nvarchar(100) [ not null ]
}

Table Promocao [headercolor: #175e7a] {
	PromocaoId uniqueidentifier [ pk, not null, unique ]
	Nome nvarchar(255)
	Descricao nvarchar(255)
	Tipo tinyint
	Valor smallint [ not null ]
	DataInicio datetime2 [ not null ]
	DataFim datetime2 [ not null ]
	Ativa bit [ not null ]
}

Table Promocao_Produto_FK [headercolor: #175e7a] {
	PromocaoId uniqueidentifier [ not null ]
	ProdutoId uniqueidentifier [ not null ]
}

Table Produto_Pedido_FK [headercolor: #175e7a] {
	ProdutoPedidoId uniqueidentifier [ pk, not null, unique ]
	ProdutoId uniqueidentifier [ not null ]
	PedidoId uniqueidentifier [ not null ]
	Quantidade smallint [ not null ]
	PrecoUnitario smallmoney [ not null ]

	indexes {
		(ProdutoId, PedidoId) [ name: 'Produto_Pedido_FK_index_0' ]
	}
}

Ref fk_Produto_Pedido_FK_ProdutoId_Produto {
	Produto_Pedido_FK.ProdutoId - Produto.ProdutoId [ delete: no action, update: no action ]
}

Ref fk_Produto_Pedido_FK_PedidoId_Pedido {
	Produto_Pedido_FK.PedidoId - Pedido.PedidoId [ delete: no action, update: no action ]
}

Ref fk_Pedido_UsuarioId_Usuario {
	Pedido.UsuarioId > Usuario.UsuarioId [ delete: no action, update: no action ]
}

Ref fk_Avaliacao_UsuarioId_Usuario {
	Avaliacao.UsuarioId > Usuario.UsuarioId [ delete: no action, update: no action ]
}

Ref fk_Avaliacao_ProdutoId_Produto {
	Avaliacao.ProdutoId > Produto.ProdutoId [ delete: no action, update: no action ]
}

Ref fk_Endereco_UsuarioId_Usuario {
	Endereco.UsuarioId > Usuario.UsuarioId [ delete: no action, update: no action ]
}

Ref fk_Favoritos_ProdutoId_Produto {
	Favoritos.ProdutoId > Produto.ProdutoId [ delete: no action, update: no action ]
}

Ref fk_Favoritos_UsuarioId_Usuario {
	Favoritos.UsuarioId > Usuario.UsuarioId [ delete: no action, update: no action ]
}

Ref fk_Pagamento_PedidoId_Pedido {
	Pagamento.PedidoId - Pedido.PedidoId [ delete: no action, update: no action ]
}

Ref fk_Estoque_ProdutoId_Produto {
	Estoque.ProdutoId - Produto.ProdutoId [ delete: no action, update: no action ]
}

Ref fk_Subcategoria_CategoriaId_Categoria {
	Subcategoria.CategoriaId > Categoria.CategoriaId [ delete: no action, update: no action ]
}

Ref fk_Produto_SubcategoriaId_Subcategoria {
	Produto.SubcategoriaId > Subcategoria.SubcategoriaId [ delete: no action, update: no action ]
}

Ref fk_Promocao_Produto_FK_ProdutoId_Produto {
	Promocao_Produto_FK.ProdutoId > Produto.ProdutoId [ delete: no action, update: no action ]
}

Ref fk_Promocao_Produto_FK_PromocaoId_Promocao {
	Promocao_Produto_FK.PromocaoId > Promocao.PromocaoId [ delete: no action, update: no action ]
}